version: 1.0.0-{build}
branches:
  only:
  - master
pull_requests:
  do_not_increment_build_number: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: K5J/3pUKGrNQVjIywrUCWMWilnoNb1jlNFgfyOx6TJm87jLq3ryaSaZB0UpUvaSp
  COVER_FILTER: '+[Dispenser*]* -[*Tests]*'
image: Visual Studio 2019
build_script:
- ps: .\build\build.ps1 $env:APPVEYOR_BUILD_VERSION $env:APPVEYOR_REPO_TAG_NAME
#before_test:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
test_script:
- ps: |
    if ($true)
    {
        .\build\test.ps1
    }
artifacts:
- path: '.\artifacts\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: Uft/AgWL0ObDUb6hWLhsftRR1sNhLa5vONUcVa/2KjVAYZApxZD6ckJ+ABFQs3bB
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only
