trigger:
  branches:
    include:
    - master

resources:
  repositories:
    - repository: templates
      type: github
      name: lvermeulen/Templates
      ref: refs/tags/1.0.0
      endpoint: lvermeulen

jobs:
- job: Build
  displayName: Build Dispenser
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: templates/dotnetcore/restore_build_test.yml@templates
    parameters:
        projects: '**/*.csproj'
        testProjects: 'test/**/*.csproj'
        buildConfiguration: 'Debug'
