trigger:
  branches:
    include:
    - master

resources:
  repositories:
    - repository: templates
      type: github
      name: lvermeulen/Templates
      ref: refs/tags/1.0.0
      endpoint: lvermeulen

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'windows-2019'
    steps:
    - template: templates/dotnetcore/restore_build_test.yml@templates
      parameters:
          projects: '**/*.csproj'
          testProjects: 'test/**/*.csproj'
          buildConfiguration: 'Release'
    - task: CopyFiles@2
      displayName: 'Copy Files'
      inputs:
        SourceFolder: '$(Build.BinariesDirectory)'
        Contents: '**/bin/**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true
        OverWrite: true

- stage: Publish
  jobs:
  - job: Publish
    displayName: Publish
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        downloadPath: '$(System.ArtifactsDirectory)'
        artifactName: 'drop'
    - template: templates/dotnetcore/pack_push.yml@templates
      parameters: 
        projectsToPack: 'src/**/*.csproj'
        buildConfiguration: 'Release'
        nupkgFolder: '$(Build.ArtifactStagingDirectory)'
        nugetServiceConnectionName: 'NuGet'
