trigger:
  branches:
    include:
    - master

jobs:
- job: Build
  displayName: Build Dispenser
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: templates/dotnetcore/restore_build_test.yml
    parameters:
        projects: '**/*.csproj'
        testProjects: 'test/**/*.csproj'
        buildConfiguration: 'Release'
